//! `cargo dacc emit all [--check]` — файлы-директивы агентов. Записанный файл
//! коммитится обычным ритуалом; `--check` сверяет свежесть без записи.

use super::scan_args;
use crate::code;
use crate::work::{refused, usage, Context, Refusal};
use std::ffi::OsString;
use std::fs;

pub(super) fn run(args: &[OsString]) -> Result<u8, Refusal> {
    let scan = scan_args(args, "emit all [--check]")?;
    if scan.status.is_some() || scan.file.is_some() {
        return Err(usage(code::USAGE, "emit all [--check]"));
    }
    if scan.position.as_deref() != Some("all") {
        return Err(usage(code::USAGE, "emit all [--check]"));
    }
    let context = Context::open()?;
    let text = directives(&context.repo.config);
    let path = context.repo.root.join("AGENTS.md");
    if scan.check {
        let committed = fs::read_to_string(&path).unwrap_or_default();
        if committed != text {
            return Err(refused(
                code::DIRECTIVES_STALE,
                "AGENTS.md is stale: run cargo dacc emit all",
            ));
        }
        println!("AGENTS.md is fresh");
        return Ok(0);
    }
    fs::write(&path, text).map_err(|error| {
        refused(
            code::FILE_NOT_READ,
            format!("AGENTS.md not written: {error}"),
        )
    })?;
    println!("AGENTS.md written");
    Ok(0)
}

/// Текст директивы агентов: навигация, ритуалы и что отвечают команды.
/// Правила коммитов продукта берутся из настройки, а не повторяются руками.
fn directives(config: &crate::config::Config) -> String {
    let mut out = String::from(
        "# Agent directives\n\n\
         Generated by `cargo dacc emit all`; `cargo dacc emit all --check` verifies\n\
         this file is fresh. Do not edit it by hand — the generator is the source.\n\n\
         ## Navigation\n\n\
         - `cargo dacc map [--format json]` — the registry map: thrusts, slices,\n\
         \x20 works with journal states, and counters.\n\
         - `cargo dacc where --file <path> [--format json]` — a place in code: its\n\
         \x20 `#[doc_anchor]` markup, the documents citing it, the related works.\n\
         - `cargo dacc work state [<w-slug>]` and `cargo dacc metrics` — work states\n\
         \x20 and counters from the journal fold.\n\
         - Do not navigate the registry with find, grep or ls; ripgrep is allowed\n\
         \x20 for sources only.\n\n\
         ## Rituals\n\n\
         - Every change has a basis in the plan: a work item with an origin.\n\
         - Commits go through `cargo dacc commit -F <message-file> -- <paths>`: the\n\
         \x20 subject is `[TYPE](scope): summary`, and the trailer is\n\
         \x20 `Dacc-Work: w-slug`.\n\
         - `cargo dacc work land <w-slug>` lands with a proof on the tree; a defect\n\
         \x20 fix — the Divergence origin — or an irreversible change lands only with\n\
         \x20 `--red-before <test>`; `--mutation-proof <check>` and\n\
         \x20 `--anti-vacuum <subject>` state the other anti-vacuous proofs.\n\
         - A slice closes on its outcome: `cargo dacc slice close <s-slug>`.\n\n\
         ## Product settings\n\n",
    );
    out.push_str(&format!(
        "- Commit types: {}.\n",
        config.commit_types.join(", ")
    ));
    out.push_str(&format!(
        "- Subject limit: {} characters.\n",
        config.subject_limit
    ));
    out.push_str(&format!("- Commit rules: {}.\n", config.commit_rules));
    out
}
