//! Скан реестров слоя работы: направления, срезы, единицы работы.
//!
//! Устроен как скан решений: один документ — один файл с каноническим
//! именем, константа-ссылка на каждый, сверка идентификатора с компилятором.
//! Сверх того порождается правило, связывающее две записи: радиус работы не
//! выше потолка её среза. Оно вычисляется в `const`, поэтому нарушение —
//! ошибка компиляции, а не находка валидатора.

use crate::{ScanError, ScannedSlug};
use dacc_core::anchor_rules::slug_ident;
use std::{fmt::Write as _, path::Path};

/// Вид реестра слоя работы и имена того, что для него порождается.
pub struct PlanKind {
    macro_name: &'static str,
    module: &'static str,
    reference: &'static str,
    record: &'static str,
    item: &'static str,
    all: &'static str,
    /// Запись вида в документации порождённого кода: «Slice 3».
    noun: &'static str,
    /// Он же строчной буквой: «Reference to slice 3». Падежей у английского
    /// нет, но регистр в середине фразы другой, поэтому форма отдельная.
    lower: &'static str,
    /// Множественное число: «References to slices».
    plural: &'static str,
}

/// Реестр направлений.
pub const THRUSTS: PlanKind = PlanKind {
    macro_name: "thrust",
    module: "thrust",
    reference: "ThrustRef",
    record: "Thrust",
    item: "THRUST",
    all: "ALL_THRUSTS",
    noun: "Thrust",
    lower: "thrust",
    plural: "thrusts",
};

/// Реестр срезов.
pub const SLICES: PlanKind = PlanKind {
    macro_name: "slice",
    module: "slice",
    reference: "SliceRef",
    record: "Slice",
    item: "SLICE",
    all: "ALL_SLICES",
    noun: "Slice",
    lower: "slice",
    plural: "slices",
};

/// Реестр единиц работы.
pub const WORK: PlanKind = PlanKind {
    macro_name: "work",
    module: "work",
    reference: "WorkRef",
    record: "WorkItem",
    item: "WORK",
    all: "ALL_WORK",
    noun: "Work item",
    lower: "work item",
    plural: "work items",
};

/// Реестр обязательств (решение 35).
pub const OBLIGATIONS: PlanKind = PlanKind {
    macro_name: "obligation",
    module: "obligation",
    reference: "ObligationRef",
    record: "Obligation",
    item: "OBLIGATION",
    all: "ALL_OBLIGATIONS",
    noun: "Obligation",
    lower: "obligation",
    plural: "obligations",
};

/// Сканирует каталог реестра одного вида.
pub fn scan_plan(dir: &Path, kind: &PlanKind) -> Result<Vec<ScannedSlug>, ScanError> {
    crate::scan_slug_dir(dir, kind.macro_name)
}

/// Порождает модули файлов, модуль констант-ссылок, сверку идентификаторов
/// и список записей вида.
pub fn emit_plan(entries: &[ScannedSlug], kind: &PlanKind) -> String {
    let mut out = String::from("// GENERATED by dacc-scan. Do not edit.\n\n");
    // Каждый публичный элемент документирован: порождённый код собирается под
    // строгим профилем lints продукта (решение 16).
    for e in entries {
        let ident = slug_ident(&e.slug);
        let slug = e.slug.as_str();
        let file = e.file.as_str();
        let _ = writeln!(
            out,
            "/// {} {}.\n#[path = {file:?}]\npub mod {ident};",
            kind.noun, slug
        );
    }

    let _ = writeln!(
        out,
        "\n/// References to {}: a path to a constant instead of a number.\n#[allow(non_upper_case_globals, unused_imports)]\npub mod {} {{\n    use dacc_core::{};",
        kind.plural, kind.module, kind.reference
    );
    for e in entries {
        let ident = slug_ident(&e.slug);
        let slug = e.slug.as_str();
        let _ = writeln!(
            out,
            "    /// Reference to {low} {slug}.\n    pub const {ident}: {r} = {r}::__from_scan({slug:?});",
            low = kind.lower,
            r = kind.reference
        );
    }
    out.push_str("}\n\n");

    let _ = writeln!(
        out,
        "\n/// All {} of the registry.\npub static {}: &[&dacc_work::{}] = &[",
        kind.plural, kind.all, kind.record
    );
    for e in entries {
        let ident = slug_ident(&e.slug);
        let _ = writeln!(out, "    &{}::{},", ident, kind.item);
    }
    out.push_str("];\n\n");
    out
}

/// Утверждения «радиус работы не выше потолка среза». Порождаются после
/// списков срезов и работ: ссылаются на `ALL_SLICES`.
pub fn emit_work_checks(work: &[ScannedSlug]) -> String {
    let mut out = String::from(
        "// The radius of a work item is within its slice ceiling — the compiler evaluates it.\n",
    );
    for w in work {
        let ident = slug_ident(&w.slug);
        let _ = writeln!(
            out,
            "const _: () = assert!(dacc_work::radius_within_slice(&{ident}::WORK, ALL_SLICES), \"dacc: the radius of {ident} is above the ceiling of its slice\");",
        );
    }
    out
}

/// Утверждение «каждое обязательство погашено приземлённой работой с
/// происхождением `WorkOrigin::Obligation`» (решение 35).
/// Порождается, когда в реестре есть обязательства: правило связывает
/// обязательства, работы и свёртку журнала, а вычисляет его компилятор.
pub fn emit_obligation_checks(obligations: &[ScannedSlug]) -> String {
    if obligations.is_empty() {
        return String::new();
    }
    String::from(
        "// Every obligation is redeemed by a landed work with WorkOrigin::Obligation — the compiler evaluates it (decision 35).\nconst _: () = assert!(dacc_work::obligations_redeemed(ALL_OBLIGATIONS, ALL_WORK, WORK_STATES), \"dacc: an obligation is not redeemed by a landed discharge work\");\n",
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Status;
    use std::fs;

    fn registry(tag: &str, files: &[(&str, &str)]) -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(format!("dacc-plan-{tag}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        for (name, text) in files {
            fs::write(dir.join(name), text).unwrap();
        }
        dir
    }

    const WORK_1: &str = "dacc_work::work!(\"w-001\", title: NonEmptyStr::new(\"x\"),);";

    #[test]
    fn scans_work_with_canonical_names() {
        let dir = registry("ok", &[("w-001.rs", WORK_1)]);
        let found = scan_plan(&dir, &WORK).unwrap();
        assert_eq!(found[0].slug, "w-001");
    }

    #[test]
    fn rejects_non_slug_work_file() {
        let dir = registry("bad", &[("W1.rs", WORK_1)]);
        let err = scan_plan(&dir, &WORK).expect_err("W1.rs принят");
        assert!(err.to_string().contains("slug id"), "{err}");
    }

    #[test]
    fn emits_refs_list_and_radius_checks() {
        let entries = vec![ScannedSlug {
            slug: "w-001".into(),
            status: Status::Draft,
            file: "/x/w-001.rs".into(),
        }];
        let code = emit_plan(&entries, &WORK);
        assert!(
            code.contains("pub const w_001: WorkRef = WorkRef::__from_scan(\"w-001\");"),
            "{code}"
        );
        assert!(
            code.contains("pub static ALL_WORK: &[&dacc_work::WorkItem]"),
            "{code}"
        );
        assert!(
            emit_work_checks(&entries).contains("radius_within_slice(&w_001::WORK, ALL_SLICES)")
        );
    }

    /// Решение 35: реестр обязательств порождает ссылки и список.
    #[test]
    fn emits_obligations_list() {
        let entries = vec![ScannedSlug {
            slug: "o-fix-x".into(),
            status: Status::Draft,
            file: "/x/o-fix-x.rs".into(),
        }];
        let code = emit_plan(&entries, &OBLIGATIONS);
        assert!(
            code.contains(
                "pub const o_fix_x: ObligationRef = ObligationRef::__from_scan(\"o-fix-x\");"
            ),
            "{code}"
        );
        assert!(
            code.contains("pub static ALL_OBLIGATIONS: &[&dacc_work::Obligation]"),
            "{code}"
        );
    }

    /// Решение 35: скан порождает утверждение погашения только при наличии
    /// обязательств; пустой реестр обязательств утверждения не порождает.
    #[test]
    fn emits_obligation_redemption_check_only_when_needed() {
        let entry = ScannedSlug {
            slug: "o-fix-x".into(),
            status: Status::Draft,
            file: "/x/o-fix-x.rs".into(),
        };
        let code = emit_obligation_checks(&[entry]);
        assert!(
            code.contains("obligations_redeemed(ALL_OBLIGATIONS, ALL_WORK, WORK_STATES)"),
            "{code}"
        );
        assert!(emit_obligation_checks(&[]).is_empty());
    }
}
