[book]
title = "DACC"
authors = ["Anishchuk Sergei"]
language = "ru"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "dioxus"
preferred-dark-theme = "dioxus"
git-repository-url = "https://github.com/anishukserg/dacc"
